atlassian/data-center-helm-charts

src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Chart.yaml, src/main/charts/jira/Chart.yaml
=> DCNG-853 Updated products' charts

src/main/charts/bitbucket/templates/tests/test-database-connectivity.yaml, src/main/charts/confluence/templates/tests/test-database-connectivity.yaml, src/main/charts/jira/templates/tests/test-database-connectivity.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Signed-off-by: Bartosz Kwiatek <bkwiatek@atlassian.com>
DCNG-899 Added service account to db-connectivity-test
=> DCNG-899 Added service account to db-connectivity-test

src/test/charts/functest/templates/ingress-EKS.yaml, src/test/charts/functest/templates/ingress-KITT.yaml, src/test/charts/functest/templates/service-expose-node.yaml, src/test/charts/functest/values.yaml, src/test/config/jira/helm_parameters, src/test/scripts/helm_install.sh
In the light of @kennymacleod 's #15 PR, this might need to change. Let's discuss as it is now and I'll refactor later if necessary.
=> DCNG-881: Create services and ingress routes to access individual nodes

src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/PersistenceTest.java, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
Same thing as I already did with Jira, but now for the other products.
=> DCNG-893 disable PVs by default on Bitbucket and Confluence

INSTALL.md
The documentation on README.rd is not clear in terms up how to scale up/down the data center after installation.
=> Modified the documentation for scaling up/down the Data Center cluster

src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/jira/templates/_helpers.tpl, src/test/java/test/VolumesTest.java, src/test/java/test/model/Product.java
=> Fix gid value

src/test/scripts/download_logs.sh
corrected log retrieval for pods with multiple containers and fixed ingress definition fetching
=> helm_uninstall.sh fixes

pom.xml, src/test/java/test/postinstall/PostInstallStatusTest.java, src/test/java/test/postinstall/Utils.java
Adds a new java test that gets run in the "final tasks" section of the bamboo plan, and which verifies the state of the pods and their containers in the product statefulset.
Hopefully this will be useful, but we can tweak it as necessary.
=> DCNG-1045 Add java test to verify post-install state

src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/jira/templates/_helpers.tpl
This should fix the error where if you have more then one plugin / library specified it will give the following error in helm:
```
Error: UPGRADE FAILED: YAML parse error on jira/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 100:
```
=> feat(range): Fix support for multiple plugins

src/main/charts/bitbucket/README.md, src/main/charts/confluence/README.md, src/main/charts/jira/README.md
This is autogenerated via https://github.com/norwoodj/helm-docs
=> Update documentation for 0.6.0 release

.github/workflows/maven.yml
Currently the actions are not running on PRs from forks (as they don't push into our repository)
=> Update Github Actions to run on PRs

src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Chart.yaml, src/main/charts/jira/Chart.yaml, src/test/java/test/HelmLintTest.java, src/test/java/test/helm/Helm.java, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Update the application versions to the latest
- Confluence and Bitbucket are using the latest released version
- Jira is using latest LTS version
Added `helm lint` test
=> Update application versions

README.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Chart.yaml, src/main/charts/jira/Chart.yaml
Preparation for publishing on [ArtifactHUB.io](https://artifacthub.io)
- add icons to charts
- change home to point to the product description
- add source link to the docker images
- simplified README.md
- add support disclaimer
- add note about feedback
=> Update charts descriptors

src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/values.yaml, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/main/charts/jira/values.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
I have created an automated workflow that should release the helm charts when it sees a new version in the `Chart.yaml` file:
https://github.com/atlassian-labs/data-center-helm-charts/blob/master/.github/workflows/helm_release
Merging this PR should trigger it and release new versions 🤞
=> Release 0.7.0

src/main/charts/crowd/.helmignore, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/NOTES.txt, src/main/charts/crowd/templates/_fluentd_templates.tpl, src/main/charts/crowd/templates/_helpers.tpl, src/main/charts/crowd/templates/clusterrole.yaml, src/main/charts/crowd/templates/clusterrolebinding.yaml, src/main/charts/crowd/templates/config-jvm.yaml, src/main/charts/crowd/templates/configmap-fluentd.yaml, src/main/charts/crowd/templates/ingress.yaml, src/main/charts/crowd/templates/nfs-permission-fixer.yaml, src/main/charts/crowd/templates/service.yaml, src/main/charts/crowd/templates/serviceaccount.yaml, src/main/charts/crowd/templates/shared-home-pvc.yaml, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/crowd/templates/tests/test-application-status.yaml, src/main/charts/crowd/templates/tests/test-shared-home-permissions.yaml, src/main/charts/crowd/values.yaml
This crowd chart was created based on the confluence chart.
Please let me know if any additional efforts are required.
=> initial Crowd Helm Chart based on Confluence Helm Chart

src/test/scripts/helm_uninstall.sh
Uninstall wasn't updated correctly for the new test NFS server `yaml`.
=> Fix NFS cleanup

src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/ingress.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/ingress.yaml, src/main/charts/jira/values.yaml
Added ingress.host into values.yaml with corresponding value injection in ingress.yaml for all apps. Defaults to "/"
=> Allow for the ingress path's to be configurable.

src/main/charts/confluence/templates/ingress-setup.yaml, src/main/charts/confluence/templates/ingress.yaml, src/test/java/test/IngressTest.java, src/test/java/test/model/KubeResource.java
Followup from https://github.com/atlassian-labs/data-center-helm-charts/pull/134
=> Add Ingress path to Confluence setup ingress and add tests

README.md
* Explicitly mention Beta
* Add a link to Atlassian Community
* Create a feedback section
=> Add a feedback section with Atlassian Community link

src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
* bump the version to v0.12.0
* added changelog to `Chart.yaml` for artifacthub
* added changes to chart changelogs
* update expected output test
The actual release will happen via Github Actions after merging to master.
=> Release v0.12.0

src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/test/java/test/RequestsTest.java, src/test/java/test/SynchronyTest.java, src/test/java/test/model/Container.java, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/confluence/values.yaml
* added resources into Synchrony container
* added tests
* enabled synchrony by default for the expected outcome test
=> DCKUBE-527: Fix Synchrony resource requests and limits

src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
=> DCKUBE-529: Update product versions to latest

src/main/charts/confluence/README.md, src/main/charts/confluence/templates/service.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/service.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/service.yaml, src/main/charts/jira/values.yaml, src/test/java/test/ServiceTest.java, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
* add service annotations
* fix expectations tests
* add unit test
* update documentation
Credit for the annotations goes to @aschbacd. Sorry, I have tried to fix it on your branch but the forking workflow didn't work for me.
=> Add Service annotations

docs/docs/README.md, docs/docs/installation/INSTALLATION.md, docs/docs/installation/MIGRATION.md, docs/docs/installation/PREREQUISITES.md
Updated file to include reference to migrating to K8s
=> Update INSTALLATION.md and add MIGRATION.md

docs/docs/README.md, docs/docs/operations/TROUBLESHOOTING.md, docs/docs/troubleshooting/TROUBLESHOOTING.md
Ideally, we would start collecting examples of common failures and problems in a form of:
* Symptoms
* Investigation
* Potential fixes
But for now, I don't have a concrete list to put here. I am open to suggestions.
=> DCKUBE-475: Initial troubleshooting document 

.atlassian/OWNER, LICENSE, README.md, docs/mkdocs.yml
As part of Credo Checklist actions
=> DCKUBE-578 - Fulfils Credo checklist requirements

docs/docs/userguide/resource_management/REQUESTS_AND_LIMITS.md
Clarify resource requests for the applications
=> DCKUBE_408-clarify-resource-requests

docs/docs/examples/database/AMAZON_RDS.md
=> DCKUBE-623: Make database creation as a requirement more apparent

docs/docs/examples/EXAMPLES.md, docs/docs/examples/database/CLOUD_PROVIDERS.md, docs/docs/examples/ingress/CONTROLLERS.md, docs/docs/examples/ingress/INGRESS_NGINX.md, docs/docs/examples/ssh/SSH_BITBUCKET.md, docs/docs/examples/storage/nfs/NFS.md, docs/docs/troubleshooting/LIMITATIONS.md, docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md, docs/docs/troubleshooting/TROUBLESHOOTING.md, docs/docs/userguide/CONFIGURATION.md, docs/docs/userguide/INSTALLATION.md, docs/docs/userguide/MIGRATION.md, docs/docs/userguide/PREREQUISITES.md, docs/mkdocs.yml
Mainly changes in two pages for readability improvements, you can see the result here:
https://nanux.github.io/data-center-helm-charts/userguide/PREREQUISITES/
https://nanux.github.io/data-center-helm-charts/userguide/CONFIGURATION/
=> Update the documentation formatting

docs/docs/userguide/INSTALLATION.md
* added `clustering` into installation flow
* separate license from bitbucket specific section
* added collapsible bitbucket automated setup section
=> Update installation file

docs/docs/userguide/CONFIGURATION.md, docs/docs/userguide/INSTALLATION.md
=> DCKUBE-minor-doc-edits

src/main/charts/jira/templates/_helpers.tpl, src/test/java/test/ClusteringTest.java
more info https://bitbucket.org/atlassian-docker/docker-atlassian-jira/src/master/README.md
=> DCKUBE-717: Bind EHCACHE ports as environmental variables

src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bamboo/README.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/main/scripts/update_versions.py, src/test/java/test/HelmOutputComparisonTest.java, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml, src/test/scripts/update_versions.py
=> DCKUBE-733: Update the product versions

docs/docs/examples/storage/.pages, docs/docs/examples/storage/additional storage/ADDTIONAL_STORAGE.md
This PR is to update document for https://github.com/atlassian/data-center-helm-charts/pull/334
Had to open new PR because of fork access restriction
=> Document update for PR#334

src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bamboo/README.md, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Changes required to release 1.3.0
=> Release 1.3.0

docs/docs/examples/storage/nfs/nfs-server-example/values.yaml
=> Add comment to location of NFS image repo

src/main/charts/confluence/Changelog.md
Added changelog that was missing in https://github.com/atlassian/data-center-helm-charts/pull/392
=> Add changelog for #390

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml
This PR releases a new version of Helm chart: 1.4.0.
=> DCD-1550: Release 1.4.0

src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Release 1.4.1 for Confluence and Jira
=> [jira, confluence] - Release 1.4.1

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Product version upgraded for release 1.5.0
Date error corrected in Changelog
=> CLIP-1575: Product version upgrade

.github/workflows/e2e-tf-deployment.yaml
Update setup-go action to the latest as it became flaky.
=> CLIP-1636: Fix the setup-go github action

src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/README.md, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/README.md, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/confluence/output.yaml
Updating the confluence version to the latest LTS version (7.19.0)
=> CLIP-1638: Update Confluence version to 7.19.0 version

src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
=> Release Confluence 1.5.1

.github/workflows/e2e-tf-deployment.yaml, pom.xml
Upgrade java dependencies used in testing.
=> Upgrade testing dependencies

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bamboo/README.md, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml
This PR bumped product versions to the latest LTS. 
Jira is in a separate PR. https://github.com/atlassian/data-center-helm-charts/pull/453
=> CLIP-1662: Updated product versions.

src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/statefulset.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Fixes #452 ,
bumps default version to `8.20.13` for security patches
=> Updating default jira version to 8.20.13

docs/docs/examples/external_libraries/EXTERNAL_LIBS.md, docs/docs/userguide/CONFIGURATION.md
=> CLIP-1518: Improved documentation

src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/SecurityContextTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
This PR adds security context for Synchrony (both in pod and container spec).
Fixes https://github.com/atlassian/data-center-helm-charts/issues/393
=> CLIP-1500: Add security context for synchrony

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
=> CLIP-1686: Release version 1.7.0

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
A major release with quite a few bugfixes and improvements
=> CLIP-1719: Release 1.8.0

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Fix artifacthub.io annotations
=> Release 1.8.1

src/test/infrastructure/nfs-server/Chart.yaml
Description is available at https://github.com/atlassian-labs/data-center-terraform/pull/305
=> CLIP-1757: Update appVersion in nfs Helm chart

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
- [NA] I have added unit tests
- [✅] I have applied the change to all applicable products
- [✅] I have added the change description to the `changelog.md` and `Chart.yaml` files
=> Release Helm chart version 1.9.0

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
=> Helm chart version bump to 1.9.1 

src/main/charts/common/README.md
=> Update README.md to fix a typo

.github/workflows/update-lts-tags.yaml
Adding an additional step to update README.md since this action changes appVersion, and helm-docs uses data from Chart.yaml to update README.md
=> CLIP-1748: Update README.md when bumping appVersions

.github/workflows/e2e-tf-deployment.yaml
=> Add Crowd in e2e test

docs/docs/troubleshooting/LIMITATIONS.md, src/main/charts/crowd/README.md, src/main/charts/crowd/values.yaml
=> Crowd service type edge case documentation

.github/workflows/process-dashboard-test.yaml, .github/workflows/sync-grafana-dashboards.yaml, src/main/scripts/process-dashboard.py, src/main/scripts/process_dashboard.py, src/main/scripts/process_dashboard_test.py, src/main/scripts/update_grafana_dashboards.sh
The script adds the following to an existing dashboard:
* namespace and service to every query
* namespace and service as env vars to templating.list in the json, along with prometheus datasource
=> DCCLIP-511: Grafana dashboard conversion script

docs/docs/platforms/OPENSHIFT.md
=> Fix broken link to support boundaries page

.github/workflows/documentation-build.yaml, .github/workflows/documentation-deploy.yaml, .github/workflows/e2e-tf-deployment.yaml, .github/workflows/kind.yaml, .github/workflows/maven.yml, .github/workflows/prepare-release.yaml, .github/workflows/process-dashboard-test.yaml, .github/workflows/release-charts.yaml, .github/workflows/release-unit-tests.yaml, .github/workflows/sync-grafana-dashboards.yaml, .github/workflows/update-lts-tags.yaml
Old actions were using an old node version and throwing warnings for documentation.
I upgraded other actions as well when I was there.
=> Upgrade Github Actions

docs/docs/containers/BAMBOO-AGENT.md, docs/docs/containers/BAMBOO.md
* BAM-25843: Fix run command with proper bambooAgentVolume mountpoint syntax
=> BAM-25843: Fix agent run commands data-center-helm-charts repo

docs/docs/containers/BITBUCKET-MESH.md, docs/docs/containers/BITBUCKET.md, docs/docs/userguide/CONFIGURATION.md
- Adding more information for Bitbucket and Bitbucket Mesh configuration files.
- Documenting the syntax translation for the properties.
=> SCALE-122: Document Bitbucket property translation

docs/docs/examples/storage/nfs/NFS.md
Clarify the disclaimer regarding NFS helm chart and NFS server requirements.
=> Update documentation related to Bitbucket shared home requirements

docs/docs/examples/storage/nfs/NFS.md, docs/docs/userguide/CONFIGURATION.md, docs/docs/userguide/PREREQUISITES.md
Rather than including detailed Bitbucket shared home requirements, we will link users to official supported platforms as they are the most up to date.
=> Replace detailed shared home restrictions with link to official supported platforms

docs/docs/containers/BAMBOO.md
Document ATL_TOMCAT_PROTOCOL + general indentation
=> Noissue: Document ATL_TOMCAT_PROTOCOL + general indentation

docs/docs/containers/BAMBOO.md
=> Noissue/ktlo Use `CODE` 

docs/docs/containers/BAMBOO.md
=> Noissue: Document ATL_TOMCAT_KEY_ALIAS
