atlassian/data-center-helm-charts

src/test/config/bitbucket/helm_parameters, src/test/config/confluence/helm_parameters, src/test/config/confluence/ingress-KITT.yaml, src/test/config/jira/helm_parameters, src/test/config/jira/ingress-KITT.yaml, src/test/scripts/helm_install.sh
Adds a bit more to the `helm_install.sh` script so that we use `curl` to verify that the Ingress is returning a non-zero response.
This should rule out one source of build flakiness whereby we try to talk to the product before the ingress is ready.
=> DCNG-874 Use curl to ping ingress URI until we get a sensible response

src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/clusterrole.yaml, src/main/charts/confluence/templates/clusterrolebinding.yaml, src/main/charts/confluence/templates/serviceaccount.yaml, src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/test/config/confluence/values-EKS.yaml, src/test/config/confluence/values-KITT.yaml, src/test/config/confluence/values.yaml, src/test/java/test/HelmOutputComparisonTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
Currently, our Helm charts requires the customer to pre-configure a `ServiceAccount`, `ClusterRole` and `ClusterRoleBinding`. In the case of Confluence and Bitbucket, this requires very specific role permissions in order for peer discovery to work, and this isn't really something we want customers to have to do.
So I've added those 3 resources to the Confluence Helm chart, with corresponding entries in `values.yaml` to control how they get expressed. By default, all 3 will be created automatically, with generated names, but the customer can pick their own names, or disable their creation entirely.
I've also changed the `values.yaml` that we use for EKS so that we *do* use the generated `ServiceAccount`, `ClusterRole` and `ClusterRoleBinding`, so that we exercise this part of the chart in …
=> Add ServiceAccount and ClusterRole to Confluence chart

src/main/charts/jira/templates/_helpers.tpl, src/main/charts/jira/templates/serviceaccount.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/config/jira/values-EKS.yaml, src/test/config/jira/values-KITT.yaml, src/test/config/jira/values.yaml, src/test/resources/expected_helm_output/jira/output.yaml
This is similar to #17 which adds a `ServiceAccount` to the Confluence chart, but this time for Jira.
Note that it's simpler for Jira, with No `ClusterRole` or `ClusterRoleBinding`, since Jira does not talk to the Kubernetes API and does not need special permissions. We still need a `ServiceAccount` as a place to attach the image pull credentials, though.
=> DCNG-894 Add a ServiceAccount to the Jira chart

src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/templates/clusterrole.yaml, src/main/charts/bitbucket/templates/clusterrolebinding.yaml, src/main/charts/bitbucket/templates/serviceaccount.yaml, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/jira/templates/statefulset.yaml, src/test/config/bitbucket/values-CUSTOM.yaml, src/test/config/bitbucket/values-EKS.yaml, src/test/config/bitbucket/values-KITT.yaml, src/test/config/bitbucket/values.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Following on from #17 with Confluence and #18 with Jira, we now add a `ServiceAccount`, `ClusterRole` and `ClusterRoleBinding` for the Bitbucket chart, and as before, changing `values-EKS.yaml` so that we use the generated service account rather than the pre-created one.
=> Add ServiceAccount/ClusterRole[Binding] to Bitbucket chart

src/main/charts/bitbucket/templates/nfs-permission-fixer.yaml, src/main/charts/bitbucket/templates/tests/test-application-status.yaml, src/main/charts/bitbucket/templates/tests/test-database-connectivity.yaml, src/main/charts/bitbucket/templates/tests/test-required-values.yaml, src/main/charts/bitbucket/templates/tests/test-shared-home-permissions.yaml, src/main/charts/confluence/templates/nfs-permission-fixer.yaml, src/main/charts/confluence/templates/tests/test-application-status.yaml, src/main/charts/confluence/templates/tests/test-database-connectivity.yaml, src/main/charts/confluence/templates/tests/test-required-values.yaml, src/main/charts/confluence/templates/tests/test-shared-home-permissions.yaml, src/main/charts/jira/templates/nfs-permission-fixer.yaml, src/main/charts/jira/templates/tests/test-application-status.yaml, src/main/charts/jira/templates/tests/test-database-connectivity.yaml, src/main/charts/jira/templates/tests/test-required-values.yaml, src/main/charts/jira/templates/tests/test-shared-home-permissions.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml, src/test/scripts/helm_install.sh
Adds the following annotation to each Chart hook we have in our charts (i.e. the chart tests, and the nfs-permission-fixers):
"helm.sh/hook-delete-policy": hook-succeeded
This will ensure that the hook pods are cleaned up when they're finished, rather than cuttering up the namespace as they currently do. Note that Helm hook pods are *not* cleaned up by `helm uninstall`, unlike every other resource in the Chart.
No, I don't know why either.
=> DCNG-897 Add hook-delete-policy to chart tests and nfs-fixer job

src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/config/bitbucket/values-EKS.yaml, src/test/config/bitbucket/values-KITT.yaml, src/test/java/test/IngressTest.java, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
The Bitbucket Helm chart allows the Tomcat "scheme" and "secure" config properties to be configured via chart vaues, but the other products' charts do not.
This PR makes them consistent by using the same value structure for all 3. In the process I've renamed the `bitbucket.proxy` structure to `bitbucket.ingress` (and also for confluence+jira), since the ingress is the kubernetes terminoogy for what the Bitbucket docs call a "proxy".
=> DCNG-927 Make Tomcat https/secure config consistent between products

src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/test/java/test/ElasticSearchTest.java
Adds a new optional structure to the Bitbucket chart values, allowing for the declaration of the ElasticSearch base URL and credentials.
It's pretty basic at this point, but means the customer won't have to manually specify the additional environment varables themselves.
It mandates that the credentials are stored in a Kubernetes secret, consistent with the other optional credentials in the charts.
=> DCNG-906 Add support for declaring ElasticSearch properties

src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/ingress.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/charts/functest/templates/ingress-EKS.yaml, src/test/config/bitbucket/values-EKS.yaml, src/test/config/bitbucket/values-KITT.yaml, src/test/config/confluence/values-EKS.yaml, src/test/config/jira/values-EKS.yaml, src/test/java/test/IngressTest.java, src/test/java/test/model/Kind.java
After much head-scratching about how Ingresses are defined across different Kubernetes API versions, I've added an Ingress template to each of our Helm charts.
By default, the Ingress is not created, the customer will have to set the `create` value to `true`. The customer also has to specify the `host` value, plus the annotations corresponding to the specific Ingress controller that the customer hapens to be using, e.g. ingress-nginx.
Also, because we use ingress-nginx in our EKS cluster, we can use (and test) these new Ingress templates in our EKS bamboo jobs. The KITT jobs still need to create the custom Contour Ingresses in the functest chart.
=> DCNG-892 Add Ingress templates

src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/IngressTest.java, src/test/resources/expected_helm_output/bitbucket/output.yaml
Currently, the charts have config values for the `SERVER_SCHEME` and `SERVER_SECURE` env vars. The values for these must be consistent, and are difficult to describe at the level of abstraction that the Helm charts operate at. There's no reason this can't be represented in the charts as a single boolean value, `https`, from which the 2 env vars can be derived.
=> DCNG-892 simplify config of https/http

src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/ingress.yaml, src/main/charts/jira/values.yaml, src/test/java/test/IngressTest.java
This PR:
* adds optional TLS configuration to ingress spec. It's not uncommon that TLS secrets are used in Ingress spec (rather than the ingress controller is configured with a wildcard TLS secret). For example, this is convenient when using cert-manager.
* adds a simple test verifying host and secret are set in spec
* update helm docs
=> Add optional TLS to ingress spec

src/test/config/bitbucket/values-EKS.yaml, src/test/config/confluence/values-EKS.yaml, src/test/config/jira/values-EKS.yaml
so that they do not interfere with performance tests.
When I used 
```
nodeSelector:
node_purpose: ci 
```
[the tests passed](https://server-gdn-bamboo.internal.atlassian.com/browse/DCNG-K8SJIRA-468), while when I used 
```
nodeSelector:
node_purpose: bitcoin-digging
```
[the tests failed](https://server-gdn-bamboo.internal.atlassian.com/browse/DCNG-K8SJIRA-469).
=> DCNG-869: In EKS run CI only on the ci-tagged nodes

src/test/scripts/helm_install.sh
Very low priority. This is something I encountered when using the script the first time. As at that point everything was new to me, I had to scratch my head a few times before I understood the problem. Maybe we can save someone some minutes of their life.
I know this guide only talks about OS X, but I suppose the update is easier for Linux users, so no guide is necessary.
=> DCNG-942: Add a comment about updating Bash

README.md
It looks like it was intended to link to `INSTALL.md` in the root folder.
=> Link the current installation documentation

src/test/config/bitbucket/helm_parameters, src/test/scripts/helm_install.sh, src/test/scripts/helm_uninstall.sh
Surprise, surprise, we need direct node access for BB tests too (otherwise user deletion is problematic because it has -  an intended - cluster propagation delay).
=> DCNG-890 - Fix Bitbucket test failure for 2 nodes

src/test/config/bitbucket/values-EKS.yaml
Now that we have NFSv3 support in the cluster, we don't need any overrides.
=> use mount options from the PV definition

pom.xml, src/test/config/bitbucket/values-KITT.yaml, src/test/config/confluence/values-EKS.yaml, src/test/config/confluence/values-KITT.yaml, src/test/config/jira/values-EKS.yaml, src/test/config/jira/values-KITT.yaml, src/test/resources/shared-home-browser.yaml, src/test/scripts/helm_install.sh, src/test/scripts/helm_uninstall.sh
Enable translation of the `values-KITT.yaml` file with different values to deploy in a different namespace.
Example:
`mvn clean install -Dshared.pvc.name=efs-pvc-dcd -Dkubernetes.target.namespace=dcd`
=> DCKUBE-44: Generify parameters

src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/jira/templates/_helpers.tpl, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/config/confluence/values.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Due to the way that the Jira+Confluence applications are constructed, with the application deployed as a WAR into Tomcat, the Tomcat logs (including the access logs) are stored in a different place in the filesystem to the application logs. 
Currently, the application logs are a sub-directory of the local-home volume, but the tomcat+access logs are just being stored on the container's internal filesystem.
This PR captures those tomcat+access logs into the local-home volume. It does this by double-mounting the local-home volume on to two separate paths in the container. The first mount point is the existing one (which captures the application logs due to them being in the `logs` sub-directory), but now I've added another mount point for the local-home volume, so that the Tomcat logs …
=> DCNG-977 Capture Jira+Confluence access logs into local-home volume

src/test/scripts/download_logs.sh
Correlating the existing format with test failures is very hard. New format:
```
2021-01-17T21:47:29Z..2021-01-27T21:43:23Z	Warning	FailedScheduling	Pod/shared-home-browser         persistentvolumeclaim "efs-claim" not found
2021-01-27T13:08:18Z..2021-01-27T21:45:31Z	Normal	NotTriggerScaleUp	Pod/shared-home-browser         pod didn't trigger scale-up (it wouldn't fit if a new node is added):
2021-01-27T15:01:56Z..2021-01-27T21:44:56Z	Warning	Unhealthy	Pod/dcng-k8sjira-668-jira-0         Readiness probe failed: HTTP probe failed with statuscode: 503
2021-01-27T17:06:25Z..2021-01-27T21:39:42Z	Warning	FailedMount	Pod/dcng-k8shelmtest124-2-bitbucket-shared-home-permissions-test         Unable to attach or mount volumes: unmounted volumes=[shared-home], unattached volumes=[shared-home …
```
=> improvements to events fetching

src/main/charts/confluence/templates/_fluentd_templates.tpl, src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/config-jvm.yaml, src/main/charts/confluence/templates/configmap-fluentd.yaml, src/main/charts/confluence/values.yaml
When Confluence is configured to use the fluentd log appender, it will post log events directly to the fluentd sidecar, avoiding the need to use a complicated regex to parse the human-readable log file.
=> DCNG-976 use http source for Confluence fluentd events

src/main/charts/jira/templates/_fluentd_templates.tpl, src/main/charts/jira/templates/_helpers.tpl, src/main/charts/jira/templates/config-jvm.yaml, src/main/charts/jira/templates/configmap-fluentd.yaml, src/main/charts/jira/values.yaml
Jira master now has the HTTP fluentd log4j appender configured, so now we need to change the Helm chart to activate the appropriate system property, and to replace the log tailing logic in fluent with the HTTP listener.
This has been done for Confluence already.
=> DCNG-976 Send jira logs to fluentd via http rather than log file tailing

pom.xml, src/test/java/test/postinstall/PostInstallStatusTest.java, src/test/java/test/postinstall/Utils.java
I've improved the new `PostInstallStatusTest` so that if a pod's status is marked as "pending", then it reports on the remaining CPU and memory capacity of all nodes in the cluster which have the correct node selector.
=> Post-install test improvements

pom.xml, src/test/java/test/postinstall/KubeClient.java, src/test/java/test/postinstall/PostInstallStatusTest.java, src/test/java/test/postinstall/Utils.java
Another tweak to the `PostInstallSetupTest`, so that when a pod has yet to be scheduled, it logs a dedicated message to that effect, along with the CPU and memory capacity of the nodes that the pod is capable of being scheduled on. It also tries to log the actual cpu/memory usage of those nodes, but that requires the K8S Metrics API server to be enabled/installed, which it currently isn't.
=> DCNG-1045 try to log node metrics also

src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/config-jvm.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
This system property instructs Confluence to enable collab editing on fresh install if Synchrony is deployed in separate cluster. This property has been introduced in master branch of Confluence and so far it's used only by helm charts.
=> DCKUBE-103: add a system to enable collab editing by default

src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/ContextPathTest.java
- add configuration for context path for Confluence service
- add context path to readinessProbe
- add test
Same feature as https://github.com/atlassian-labs/data-center-helm-charts/pull/86 for Confluence.
=> ISSUE-85: Add context path for Confluence

src/test/scripts/helm_install.sh
The following error was present when debug option was set to false (`-Dhelm.debug=false`)
```
+ helm install -n dcd --wait epyshnograev-confluence-pgsql --values ./src/test/scripts/postgres-values.yaml --set fullnameOverride=epyshnograev-confluence-pgsql --set image.tag=11 --set postgresqlDatabase=confluence --set postgresqlUsername=confluence --set postgresqlPassword=confluence --version 9.4.1 '' bitnami/postgresql
Error: expected at most two arguments, unexpected arguments: bitnami/postgresql
```
The issue was caused by quotes around potentially empty variable.
=> DCKUBE-205: fix the provisioning error when debug is disabled

docs/artifacthub-repo.yml
This metadata file enables us to claim ownership for the helm chart in artifacthub.io. See documentation for details:
https://artifacthub.io/docs/topics/repositories/#helm-plugins-repositories
The next step would be adding an official status badge but that is an additional process.
For now, the repository is disabled while I am onboarding the helm chart on the platform. The chart will be under `atlassian` organization.
=> Add artifacthub.io metadata file

src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Encountered the error below when spinning up Jira with the origina changes: https://github.com/atlassian-labs/data-center-helm-charts/pull/117/files
This change is to address the limitation.
```Events:
Type     Reason            Age                From                    Message
----     ------            ----               ----                    -------
Normal   SuccessfulCreate  12s                statefulset-controller  create Claim local-home-drathbone-jira-0 Pod drathbone-jira-0 in StatefulSet drathbone-jira success
Warning  FailedCreate      1s (x12 over 12s)  statefulset-controller  create Pod drathbone-jira-0 in StatefulSet drathbone-jira failed error: Pod "drathbone-jira-0" is invalid: spec.containers[0].ports[1].name: Invalid value: "ehcachePort": must contain only …
```
=> DCKUBE-272: Rename port mappings

src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/jira/templates/statefulset.yaml, src/test/java/test/AdditionalFilesTest.java, src/test/java/test/VolumesTest.java, src/test/java/test/model/Container.java, src/test/java/test/model/StatefulSet.java
Defining additionalFiles in the Jira chart resulted in:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.volumes[0]): unknown field "items" in io.k8s.api.core.v1.Volume, ValidationError(StatefulSet.spec.template.spec.volumes[1]): unknown field "items" in io.k8s.api.core.v1.Volume]
```
due to an indentation issue.
While fixing that I also noticed that additionalFiles weren't specified in Confluence's ' volumes' so I've added it there.
Bitbucket's indenting looks fine.
=> indenting jira's additionalFiles volume mounts and adding to confluence

src/test/infrastructure/storage/test-nfs-server.yaml, src/test/scripts/helm_uninstall.sh, src/test/scripts/start_nfs_server.sh
I decided to move away from the reference infrastructure. I think we are mixing two concerns together - throwaway infrastructure for testing and an example for customers. I think this is keeping it cleaner for customers.
It also separates our requirements:
* need to be able to run in the local environment (use default storage class)
* lower the computational resources (so the builds are not draining our CI capacity)
I haven't made a decision whether to remove the `test-` prefix for the resources in https://github.com/atlassian-labs/data-center-helm-charts/blob/master/reference-infrastructure/storage/nfs/nfs-server.yaml
To some degree, it is still NFS Server for testing purposes. 
Just to learn `kustomize` I've tried to see how this change would look like in it - …
=> Lower the NFS server requirements and remove storageClass

src/main/charts/confluence/templates/config-jvm.yaml
If the parameter `confluence.jvmDebug.enabled` is false, Confluence provisioning fails because of incorrectly formatted JVM arguments. This PR fixes the problem.
=> DCKUBE-205: fix a provisioning a problem when debug flag is false

src/main/charts/confluence/templates/ingress-setup.yaml, src/main/charts/confluence/templates/ingress.yaml
Right now default `/` ingress path generates double slash in Confluence ingresses:
```
rules:
- host: efims-macbook.local
http:
paths:
- path: /
backend:
serviceName: epyshnograev-confluence
servicePort: 80
- path: "//synchrony"
backend:
serviceName: epyshnograev-confluence-synchrony
servicePort: 80
```
This pull request trims the extra slash before concatenating it with subpath.
=> DCKUBE-292: fix the problem with empty ingress URL in Confluence

docs/INSTALLATION.md
There was a typo in the installation guide: helm-chart link was broken. We spent some time before actually guess to append one letter to the link :)
=> Fix broken link in the installation guide

src/main/charts/confluence/templates/synchrony-start-script.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/SynchronyTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
This adds the resources stanza, and injects those values into the generated Synchrony startup script. The resulting running command looks like:
`java -Xss2048k -Xmx1g -XX:ActiveProcessorCount=2 -classpath /opt/atlassian/confluence/confluence/WEB-INF/packages/synchrony-standalone.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/* synchrony.core sql`
=> DCKUBE-322: Add resources stanza for Synchrony and inject values into startup

src/main/charts/confluence/templates/ingress-setup.yaml
This PR will battle timeout during setup which we are seeing in Confluence builds. The problem was partially fixed before when we increased the timeout for `/setup` prefixes, but the same change must be also applied for `/bootstrap` prefixes, as they are also used in the setup.
=> DCKUBE-438: increase the timeout for /bootstrap endpoints in the same way as for /setup to avoid the ingress timeout

src/test/scripts/helm_install.sh
Override DOCKER_LTS_VERSION by DOCKER_IMAGE_VERSION when both are defined
=> DCKUBE-446: Override LTS version of product by DOCKER_IMAGE_VERSION when both are defined

src/main/charts/bitbucket/templates/NOTES.txt, src/main/charts/confluence/templates/NOTES.txt, src/main/charts/crowd/templates/NOTES.txt, src/main/charts/jira/templates/NOTES.txt
When helm chart is installed without persistent volume, a warning will be printed out in the post-install note. 
However, the warning was for Shared Home only. Now added local home PV checking as well, and made separate warnings for each, which hopefully will reduce ambiguity.
=> DCKUBE-437: Wording improvement for warning in NOTES when PV is not used

src/test/scripts/helm_install.sh, src/test/scripts/shared_home_browser_install.sh, src/test/scripts/start_nfs_server.sh
Sometimes the cluster-autoscaler takes too long to spin up new
nodes, this timeout should give enough time for it to spin up
nodes and then for the application to come up.
=> DCKUBE-429 Increase timeout for waiting for pods to come up.

src/main/charts/jira/templates/_helpers.tpl, src/main/charts/jira/templates/ingress.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/IngressTest.java
Added default value for ingress.path and also introduced ALT_PROXY_NAME and ALT_PROXY_PORT for Jira helm chart
=> DCKUBE-474: Added Jira Proxy information to helm chart

src/main/charts/confluence/templates/service.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/service.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/service.yaml, src/main/charts/jira/values.yaml
Add option for additional service annotations. Was already implemented for Bitbucket.
=> Add service annotations for Confluence, Crowd, and Jira

Makefile, docs/mkdocs.yml
The link (pencil icon on each page) is now pointing to the correct location.
Also fixed local deployment from `make`.
=> Fix the edit link on the documentation

cr.yaml
Since we have switched to using `gh-pages`, it should be possible to start using the helm releaser.
https://github.com/helm/chart-releaser-action
=> Fix the chart releaser process

src/test/infrastructure/nfs-server/templates/statefulset.yaml, src/test/infrastructure/nfs-server/values.yaml
Local execution has been broken since this change. It was trying to provision an NFS Server using the gp2 Storage Class, which is available in AWS, but not in Docker for Mac.
This pull request uses the default Storage Class for NFS Server instead. It fixes the local execution, and it's also supposed to work in AWS, since the gp2 storage class is default there.
* [Confluence build](https://server-syd-bamboo.internal.atlassian.com/browse/CONFA3CLUSTER-K8S37-2)
* [Bitbucket build](https://server-syd-bamboo.internal.atlassian.com/browse/BSERV-K8S17-4)
=> DCKUBE-593: use default storage class of the NFS server

src/main/charts/README.md.gotmpl, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md
Just a simple change to link to our docs instead of products (which are linked to cloud versions by default anyway)
=> Change the Home link to documentation

.github/ISSUE_TEMPLATE/report-issue.md
Recommended to report product bugs in Atlassian Support page instead of GitHub itself
=> DCKUBE-664: Added a recommendation to report product bugs in Atlassian Support page

src/main/charts/confluence/README.md, src/main/charts/confluence/values.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
If the Confluence node becomes unhealthy, it takes 2.5 minutes of failing `/status` checks for load balancer to exclude the node.
It's because the readiness probe has a period of 5 seconds and `failureThreshold` of 30. The product of those values is 150 seconds, which corresponds to 2 minutes and 30 seconds
In practice this means that the customer, whose session was pointing to the failed node, will continue experiencing errors for at least 2 minutes and 30 seconds until they can work with the application again.
2:30 seems like too much. There is no reason I know failover should be this long. In this pull request I'm changing the chart defaults to have 30 seconds of failover - this coincides with the reasonable timeout for HTTP request and seems like a better value for failover.
This …
=> DCKUBE-686: decrease Confluence failover time

docs/mkdocs.yml
The `mkdocs` container always fetches the latest image (it is up for discussion if this is a good thing). This will fix the tabbed content
This is now rendered in the official docs
This is after the fix
Changelog
https://squidfunk.github.io/mkdocs-material/upgrade/#pymdownxtabbed
=> [documentation] Fix the tabbed content to support mkdocs-material v8.x

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/service.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/service-ssh.yaml, src/main/charts/bitbucket/templates/service.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/service-synchrony.yaml, src/main/charts/confluence/templates/service.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/service.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/service.yaml, src/main/charts/jira/values.yaml, src/test/java/test/ServiceTest.java, src/test/java/test/model/Service.java
**What this PR does:**
New feature which allows to define a specific `loadBalancerIP` for a service type `LoadBalancer`.
This is needed f.e. to request a fix service ip with metallb.
**Reference:**
- https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
- https://metallb.universe.tf/usage/#requesting-specific-ips
=> add feature to define loadBalancerIP

docs/docs/README.md, docs/docs/troubleshooting/LIMITATIONS.md
⚠️ Only to be merged after version `1.0.0` of the Bamboo Helm charts has been cut! ⚠️
=> BAMBK8S-172: Remove 'under active development' references

src/main/charts/crowd/templates/statefulset.yaml, src/test/resources/expected_helm_output/crowd/output.yaml
**What this PR does**
add the missing link from the configmap to the ENV `JVM_SUPPORT_RECOMMENDED_ARGS`
**Current behaviour**
All configurations in the values `crowd.additionalJvmArgs` are written in the configmap, but not applied to the environment
**Exepted behaviour**
the ENV `JVM_SUPPORT_RECOMMENDED_ARGS` is set correctly
**PS**
Can you please make new chart releases for any product?
The current versions are from november/december 2021 and I really need to test all the new features (around 9 PRs) with a stable chart.
thanks!
=> [crowd]: add missing JVM_SUPPORT_RECOMMENDED_ARGS env

src/main/charts/bitbucket/templates/statefulset.yaml, src/test/java/test/BitbucketSshServiceTest.java
**What this PR does:**
Fix templating the environment variable `PLUGIN_SSH_BASEURL` with a custom port other than `22`.
**Current behaviour**
If you use following values, the value of the environment variable `PLUGIN_SSH_BASEURL` is still `ssh://testhost-ssh/` without the custom port number.
_values.yml_
```yaml
ingress:
host: test
bitbucket:
sshService:
enabled: true
port: 7999
host: testhost-ssh
```
**Exepted behaviour**
With the updated function, the result is the expected string `ssh://testhost-ssh:7999/`.
I removed the "default" templating section, because a default is already defined in the values file (https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/bitbucket/values.yaml#L462)
=> [bitbucket]: fix templating of PLUGIN_SSH_BASEURL with custom port

src/main/charts/bitbucket/templates/shared-home-pvc.yaml
**What this PR does**
Only set `volumeName` for the shared-home `persistentVolumeClaim` if explicitly defined in the values file.
**Current behaviour**
If you want to define only the shared-home `persistentVolumeClaim` without the `persistentVolume`, the field `volumeName` is always set as an empty string.
_values.yml_
```yaml
volumes:
sharedHome:
persistentVolume:
create: false
persistentVolumeClaim:
create: true
```
This behaviour can lead to problems, because the volumeName is then set by the CSI (like Longhorn, etc.). The next time you rollout the helm-chart, helm stops the upgrade with the following error:
```bash
Error: UPGRADE FAILED: cannot patch "bitbucket-shared-home" with kind PersistentVolumeClaim: PersistentVolumeClaim "bitbucket-shared-home" is invalid: spec: Forbidden: spec …
```
=> [bitbucket]: use volumeName only if explicitly defined

src/main/charts/bitbucket/templates/NOTES.txt, src/main/charts/bitbucket/templates/statefulset.yaml, src/test/java/test/ContextPathTest.java, src/test/resources/expected_helm_output/bitbucket/output.yaml
This PR is for fixing https://github.com/atlassian/data-center-helm-charts/issues/377 where readiness probe failed for Bitbucket when contextPath is populated.
=> DCD-1454: [Bitbucket] readiness probe failed on contextpath

src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/templates/_helpers.tpl, src/test/java/test/IngressTest.java
The `ATL_BASE_URL` should be appropriately set when an ingress path is supplied.
This fix will set the `ATL_BASE_URL` env that bamboo uses to set its base path. Previously the base path was misconfigured (the path was not considered) if an `ingress.path` was supplied.
=> TFKUBE-384: `ATL_BASE_URL` should be appropriately set when `ingress.path` is supplied

src/main/charts/confluence/Changelog.md, src/main/charts/jira/Changelog.md, src/main/charts/jira/README.md, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/LicenseTest.java
Remove unused `jira.license` values. Jira application doesn't support pre-seeding license and therefore can cause confusion.
=> DCD-1455: Remove jira license

.gitignore, src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bamboo/README.md, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/README.md, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/README.md, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/README.md, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/README.md, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml, src/test/scripts/product_versions.py, src/test/scripts/update_versions.py
* Updated all products to the latest LTS versions. The major bump is for Bitbucket to jump to 7.21.0 (which is the latest LTS).
* Added changelogs
* Removed the `jdk-11` suffix, I don't think it serves us or customers any purpose
The internal CI build is running https://server-syd-bamboo.internal.atlassian.com/browse/DCD-K8SHELMTEST62-2
=> Update product latest LTS versions

.github/pull_request_template.md
Add a note regarding internal Bamboo CI. It is a good habit to check the status of the build.
If/when we will move towards full deployments in Github Actions with Terraform, we can remove this.
=> Add a note regarding internal CI

src/main/charts/crowd/templates/clusterrolebinding.yaml
Fix for the following error which occurred during install of Crowd.
`Error: template: crowd/templates/clusterrolebinding.yaml:7:6: executing "crowd/templates/clusterrolebinding.yaml" at <include "common.labels" .>: error calling include: template: no template "common.labels" associated with template "gotpl"`
Change from `common.labels` to `common.labels.commonLabels` reflecting setup for [Confluence template cluterrolebinding.yaml ](https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/confluence/templates/clusterrolebinding.yaml)
The error `error calling include: template: no template "common.labels" associated with template` occurred during the installation of the Crowd chart. Identified to be the result of incorrect mapping in the common library chart. Fixed to …
=> Bug Fix: Crowd install common.label error.  clusterrolebinding.yaml

src/main/charts/bamboo-agent/Changelog.md, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/templates/ingress.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/templates/ingress.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/templates/ingress.yaml, src/main/charts/jira/values.yaml, src/test/java/test/IngressTest.java
The default value doesn't fit if i'am running the IntegrityChecker in a large cluster -> Proxy Timeout
=> Configurable ingress proxy settings

src/main/charts/bamboo-agent/templates/deployment-agent.yaml, src/main/charts/bamboo-agent/values.yaml, src/main/charts/bamboo/templates/statefulset.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/SecurityContextTest.java
Currently, helm charts enforce securityContext, most notably fsGroup is set to 2001. For instances with lots of files this is problematic due to bug https://github.com/kubernetes/kubernetes/issues/69699 (issue is fixed, but will reach GA in 1.23).
Furthermore, as you already found out, setting fsGroup doesn't work for NFS, so this step can also be skipped for that kind of storage. From my personal research I also noticed fsGroup doesn't work well with samba shares, but this needs more through testing.
This PR makes setting whole securityContext optional for Jira and main goal here is to workaround the K8s issue. By default it will still apply securityContext.
If you like it then I can apply the change for the rest of applications.
I'll appreciate if you approve it quickly, as we want to …
=> Make pod securityContext optional.

.github/workflows/e2e-tf-deployment.yaml
E2E test detects the latest release in `Deployment Automation for Atlassian DC on K8s` project to test against the latest `main` branch of the helm chart repo. 
As K8s deployment version 2.0.0 is released, `Confluence`, `Bitbucket`, and `Jira` are included to the project. The E2E test in data center helm chart project has no logic to include any application but Bamboo (is written based on version 1.x). So this PR adjust the E2E test and add needed action secrets to fix the E2E test.
=> DCD-1529: Add Bitbucket, Jira, and Confluence to E2E tests

src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/crowd/templates/_helpers.tpl, src/main/charts/crowd/templates/statefulset.yaml, src/test/java/test/IngressTest.java
Copied logic from previous DCKUBE-474 for Confluence. Consolidated jira, confluence, and bamboo tests for these settings. Separate bamboo tests for these settings were removed as these tests are the same for all 3 products.
Noticed server.xml had empty values for these settings when I was troubleshooting a Confluence issue yesterday with latest helm chart.
- [ x ] I have added unit tests
- [ x ] I have applied the change to all applicable products
- [ x ] I have added the change description to the `changelog.md` and `Chart.yaml` files
=> Add ATL_PROXY_NAME and ATL_PROXY_PORT to Confluence/Crowd

docs/docs/platforms/OPENSHIFT.md
This PR introduces a few updates to OpenShift docs, namely:
* turning off securityContext (OpenShift will do it on its own)
* add docs on how to solve permission denied errors in app installation directory (declare those as emptyDir)
=> Update OpenShift docs

src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/templates/statefulset.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/templates/synchrony-start-script.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/templates/statefulset.yaml, src/test/java/test/CustomPortTest.java, src/test/java/test/SynchronyTest.java, src/test/java/test/model/Container.java, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
* Fix the use of the custom ports for the products
* Add unit tests
* Bitbucket is not using Tomcat, therefore it needs to use a different env. property (`server.port`).
=> CLIP-1553: Use custom port for product server

src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/IngressTest.java, src/test/java/test/SynchronyTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
Closes #225 
Allows synchrony to work with or without context path that is driven from the ingress.host used for the confluence application. The context path for synchrony would always be /synchrony and that context path would be reserved for synchrony. I think it removes some of the confusion in the values.yaml around the ingress hosts and context paths and also a lot of the cross-walking of the configuration. There doesn't appear to be much benefit to have the ingress host for synchrony to be configurable as it is only for collaborative editing. A user does not necessarily route to this url directly to use collaborative editing. It just happens in the background. In most cases if the network/web server path to ingress.host is open, then the network path …
=> synchrony path fix

.github/workflows/e2e-tf-deployment.yaml
This PR bump up the version of Kubernetes to use v1beta1 apiVersion for k8s client authentication. We already fix terraform installer project (v2.02) to use the same apiVersion.
=> CLIP-1596: Fixed end to end test by bumping up k8s version

.github/workflows/e2e-tf-deployment.yaml
We didn't have scheduled the end to end test run and in no active development periods, we never find out about test failures. To give more visibility on the health of the repo we should run e2e tests in a logical period of time. 
As there is no frequent change in this repo, and e2e test is an expensive test, testing in every second day basis would be sufficient to keep an eye on the repo health and in the same time not spend much on heavy test process. 
- [] (Atlassian only) Internal Bamboo CI is passing
=> CLIP-1588: Schedule to run end to end test on every second day at 3:00am

.github/pull_request_template.md, .github/workflows/e2e-tf-deployment.yaml
Update workflow to run e2e test when PR is labeled as 'e2e'
This is a PR to test manual trigger for e2e test.
When external contributors raised PR. If required, reviewers can add 'e2e' label on the PR and this will trigger e2e test.
The condition to run e2e test after this PR is going to be:
- Push to main branch
- Labeled PR as 'e2e'
- Manual workflow dispatch
- On Schedule (https://github.com/atlassian/data-center-helm-charts/pull/424)
=> CLIP-1597: Update workflow to run e2e test when PR is labeled as 'e2e'

.github/pull_request_template.md, .github/workflows/e2e-tf-deployment.yaml
As part of the experiment, this PR will change workflow event trigger from `pull_request` to `pull_request_target`.
Given information https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
We can grant main repo's secret access to forked branch PR but still not sure which code the workflow will run on. It is worth test this.
=> CLIP-1597: Change trigger event from pull_request to pull_request_targe

.github/workflows/e2e-tf-deployment.yaml, docs/docs/assets/stylesheets/extra.css, src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/test/java/test/IngressTest.java, src/test/java/test/SynchronyTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
* synchrony path fix
* This PR is a contribution from community (https://github.com/atlassian/data-center-helm-charts/pull/420)
Merging to CLIP-1413-fix-synchrony-ingress-path branch to run e2e tests
Allows synchrony to work with or without context path that is driven from the ingress.host used for the confluence application. The context path for synchrony would always be /synchrony and that context path would be reserved for synchrony. I think it removes some of the confusion in the values.yaml around the ingress hosts and context paths and also a lot of the cross-walking of the configuration. There doesn't appear to be much benefit to have the ingress host for synchrony to be configurable as it is only for collaborative editing. A user does not necessarily route to this url directly to …
=> CLIP-1413: Fix synchrony ingress path

docs/docs/platforms/OPENSHIFT.md
A few additions to OpenShift gotchas, namely explanation of the nature of permission issues when generating config files from Jinja templates and how to fix it without attaching anyuid SCC by building a custom image from an official one.
=> A few more OpenShift tips

.github/workflows/e2e-tf-deployment.yaml
To be merged after https://github.com/atlassian-labs/data-center-terraform/pull/265
This PR adds python environment and configures aws for boto3 python client and k8s log collection script. No changes to Helm charts, just a little change to e2e workflow.
=> AWS cleanup and log colletion from k8s after e2e tests

.github/workflows/e2e-tf-deployment.yaml
Can be merged before or after https://github.com/atlassian-labs/data-center-terraform/pull/263
Adding 2 env vars (already added them to secrets) so that osquery is enabled in e2e test instances.
=> Add osquery related env vars for Terraform

src/main/charts/bamboo/Changelog.md, src/main/charts/bamboo/Chart.yaml, src/main/charts/bamboo/templates/ingress.yaml, src/main/charts/bitbucket/Changelog.md, src/main/charts/bitbucket/Chart.yaml, src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/confluence/Changelog.md, src/main/charts/confluence/Chart.yaml, src/main/charts/confluence/templates/ingress-setup.yaml, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/crowd/Changelog.md, src/main/charts/crowd/Chart.yaml, src/main/charts/crowd/templates/ingress.yaml, src/main/charts/jira/Changelog.md, src/main/charts/jira/Chart.yaml, src/main/charts/jira/templates/ingress.yaml, src/test/java/test/IngressTest.java
After Kubernetes 1.18 version, "ingress.class"'s annotation is deprecated.
So deleted that annotation and add "ingressClassName" field.
ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
=> Ingress Class Name is moved under spec field.

src/test/config/bitbucket/values-EKS.yaml
This is a small fix to Bitbucket ingress testing values. After ingress class migrated from `metadata.annotations` to `spec` changes to testing values for EKS are required.
=> Update Bitbucket ingress testing values

.github/workflows/e2e-tf-deployment.yaml
See: https://github.com/atlassian-labs/data-center-terraform/pull/270
Pinning python version to make sure pythonpath is correct (required to execute aws_clan.py script)
=> Pin Python version to 3.9.14

docs/docs/troubleshooting/LIMITATIONS.md, docs/docs/userguide/INSTALLATION.md, src/main/charts/bamboo/templates/_fluentd_templates.tpl, src/main/charts/bamboo/templates/statefulset.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/templates/_fluentd_templates.tpl, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/_fluentd_templates.tpl, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/_fluentd_templates.tpl, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/_fluentd_templates.tpl, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/ImageTest.java, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
Fixes https://github.com/atlassian/data-center-helm-charts/issues/411
A small change to values and templates to be able to pass custom image and tag to nfs permission fixes init container and fluentd sidecar (if enabled)
=> CLIP-1566: Make it possible to configure images/tags of auxiliary containers

.github/workflows/update-lts-tags.yaml
This PR adds a new workflow to be run raily. It will reuse existing script that checks the latest LTS app versions and modifies Chart.yaml and well expected output yaml (for unit tests) with new versions. If there are no changes, it'll do nothing.  If there's an **open** PR with the name "Update appVersions for DC apps", the script won't create a new one.
=> CLIP-1709: Raise PRs with the latest app versions

.github/workflows/update-lts-tags.yaml
Just a small fixup to handle 1 exit code from grep (if there are no open PRs with a pre-defined title). The workflow was failing when grep returned 1 (i.e. there are no open PRs)
=> CLIP-1709: Fix 1 exit code when fetching PRs

.github/workflows/e2e-tf-deployment.yaml
Currently, when e2e tests are kicked off, local helm charts aren't used, even though `local_helm_charts_path` [is defined](https://github.com/atlassian/data-center-helm-charts/blob/main/.github/workflows/e2e-tf-deployment.yaml#L113).
However, in [locals.tf](https://github.com/atlassian-labs/data-center-terraform/blob/main/locals.tf#L13) there's a double condition. By default, `_*install_local_chart` [is false](https://github.com/atlassian-labs/data-center-terraform/blob/6074f403035f419f842f2800cb042d572ba944bd/variables.tf#L358).
Taking a look at [Terraform logs](https://github.com/atlassian/data-center-helm-charts/actions/runs/3458274209/jobs/5786932502#step:13:756), we can see that local charts aren't used, moreover, a pretty old version is deployed (this is fixed by …
=> CLIP-1715: Use local helm charts in e2e tests

src/main/charts/confluence/values.yaml
Currently a dict is used in the default values for additionalJvmArgs, but the helm charts expects a list. Essentially this is a typo of {} instead of [].
=> Fix additionalJvmArgs parameter for Synchrony

src/main/charts/confluence/templates/_helpers.tpl, src/test/java/test/ClusteringTest.java
See: https://jira.atlassian.com/browse/SCALE-70 and https://jira.atlassian.com/browse/SCALE-71
This PR fixes hazelcast discovery for Confluence and Synchrony by explicitly setting `HAZELCAST_KUBERNETES_SERVICE_PORT ` to the value provided in values.yaml.
=> Set Hazelcast port env var for Confluence and Synchrony

src/main/charts/bamboo/templates/ingress.yaml, src/main/charts/bitbucket/templates/ingress.yaml, src/main/charts/confluence/templates/ingress.yaml, src/main/charts/crowd/templates/ingress.yaml, src/main/charts/jira/templates/ingress.yaml
ingress.tlsSecretName was used to enable https in the ingress. This forces to use a TLS secret, but in some cases the default tls secret for the
default ingress can be used.
In the case the default TLS secret for the default ingress controller should be used
it is not possible to leave ingress.tlsSecretName enpty and simply set ingress.https to true.
=> Use ingress.https to enable https in ingress

.github/workflows/maven.yml, docs/docs/userguide/PREREQUISITES.md, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Chart.yaml
Bump version of minimal supported K8s API version
=> CLIP-1644: Stop supporting 1.19-1.20 k8s

.github/workflows/dc-tests.yml, .github/workflows/kind.yaml, src/test/config/kind/common-values.yaml, src/test/config/kind/kind-config.yml, src/test/config/kind/nfs-values.yaml, src/test/scripts/kind/configure_kind.sh, src/test/scripts/kind/create_kind.sh, src/test/scripts/kind/deploy_app.sh
This PR adds a new reusable workflow (see checks in this PR below) that:
* creates a [KinD cluster](https://github.com/kubernetes-sigs/kind). Both K8S API and KinD versions are configurable.
* deploys Nginx ingress controller, NFS server and NFS client provisioner that automatically creates RWX PVs when a PVC is created
* deploys Postgres DB (Bitnami Helm chart) for each app
* deploys Bitbucket, Confluence, Jira and Bamboo (each in its own job, i.e. in its own cluster) with persistence and ingress enabled in values. The values have a few modifications related to lack of CPU, so requests had to be cut a bit. Apps supporting unattended setup use the corresponding values. Database, admin user and license env vars are added to all Helm releases. When Bamboo is deployed, Bamboo agent chart is …
=> CLIP-1721: Introduce Kubernetes in Docker (KinD) tests

.github/workflows/e2e-tf-deployment.yaml
This PR adds an official [AWS action](https://github.com/aws-actions/configure-aws-credentials) to assume a role (saved in actions secrets).
Run from the branch ✅  https://github.com/atlassian/data-center-helm-charts/actions/runs/3723318978/jobs/6314758186
Also, opened https://github.com/atlassian-labs/data-center-terraform/pull/296
=> CLIP-1729: Assume IAM role instead to get AWS credentials for tests

src/test/scripts/kind/configure_kind.sh
Bamboo and Bitbucket kind tests are failing because both apps do not proceed with unattended setup and thus can't scale and Bamboo can't register agents. The problem can only be reproduced in kind. Overriding image tag fixes the problem.
=> Use 2.0 tag of the nfs test image in kind

src/main/charts/confluence/templates/statefulset-synchrony.yaml, src/main/charts/confluence/values.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
When setting up my external Google Cloud Ingress (not using Nginx Ingress), we need the ability to configure the healthcheck path. As documented, Synchrony expects the path to include "/synchrony" to be included in all requests. If not, we were seeing healthchecks returning back a `204 No Content`.
=> feat: Added support for configuring healthcheckPath to Synchrony readinessProbe

src/main/scripts/prepare-release.py
Just two small changes:
* wrap strings in double quotes for artifacthub.io annotations
* get rid of Jira ticket key in changelog and artifacthub.io annotations
Here's example git diff:
```
--- a/src/main/charts/bamboo-agent/Chart.yaml
+++ b/src/main/charts/bamboo-agent/Chart.yaml
-  artifacthub.io/changes: |
-    - kind: changed
-      description: Fix artifact hub annotation yaml
+  artifacthub.io/changes: |-
+    - "Hello World"
+## 1.9.2
+
+**Release date:** 2023-2-16
+
+![AppVersion: 9.2.1](https://img.shields.io/static/v1?label=AppVersion&message=9.2.1&color=success&logo=)
+![Kubernetes: >=1.21.x-0](https://img.shields.io/static/v1?label=Kubernetes&message=>=1.21.x-0&color=informational&logo=kubernetes)
+![Helm: v3](https://img.shields.io/static/v1?label=Helm&message=v3&color=informat …
```
=> Prepare release script: Remove Jira keys and wrap strings in double quotes

src/test/config/bitbucket/values-KITT.yaml
Just minor cleanup to fix CI. KITT values were hardcoded for testing purposes. Mesh tests run in a different Bamboo plan
=> Skip mesh deployment to KITT

.github/workflows/release-unit-tests.yaml, src/main/scripts/prepare_release.py, src/main/scripts/prepare_release_test.py
This PR makes git log filtering in the release script a bit smarter. Once a week, [update-lts-tags workflow](https://github.com/atlassian/data-center-helm-charts/blob/main/.github/workflows/update-lts-tags.yaml) raises PRs to bump LTS appVersions. The bot writes the same commit message - `Update appVersions for DC apps`. However, when a PR is merged, by default PR number enclosed in brackets is appended to the commit message, go in git log we see `Update appVersions for DC apps (#533)`. These commits make it to Git log, and we need just one in the release notes - the latest.
Also, adding a few simple unit tests to make sure the script is doing the right job by:
* removing duplicate commit messages
* removing Update appVersions for DC apps with lower PR number, i.e. only one is left
* …
=> CLIP-1782: Improve release script and add unit tests

docs/docs/README.md, docs/docs/userguide/.pages, docs/docs/userguide/VERIFICATION.md
This PR added documentation on how to verify Hem charts.
=> CLIP-1783: Added documentation on how to verify Hem charts.

src/main/charts/crowd/templates/configmap-fluentd.yaml
Adding missing custom fluentd config to configmap template
=> Update fluentd configmap template for Crowd

.github/workflows/dc-tests.yml, .github/workflows/e2e-tf-deployment.yaml, .github/workflows/kind.yaml, src/test/config/kind/common-values.yaml, src/test/scripts/kind/deploy_app.sh
Current problems:
* KinD tests fail when trigged by PRs created from forks because secrets are not available for actions triggered by `pull_request`.
* e2e tests triggered by labeled PRs checkout code from main branch in this repo rather than a fork
With this PR merged, to run KinD tests, `kind` label needs to be added to PR (or one can manually start this workflow). Also, e2e tests will checkout code from the fork and actually test the changes
=> CLIP-1784: Multiple fixes to GitHub Actions

docs/docs/userguide/upgrades/HELM_CHART_UPGRADE.md
This PR fixes upgrade instructions that suggest the use of `--reuse-values` when upgrading Helm **chart version**. When `--reuse-values` is passed, the default values.yaml packaged in the Helm chart is ignored. As a result, if it contains some new default values that are used in templates, upgrade to a new version will fail with a templating error. We're not always adding defaults in the templates themselves.
It's ok to use `--reuse-values` when upgrading appVersion only.
=> Fix upgrade docs

.github/workflows/e2e-tf-deployment.yaml, .github/workflows/kind.yaml
Use of `${{ github.event.pull_request.head.sha }}` is more appropriate than `repository: ${{ github.event.pull_request.head.repo.full_name }}` with `ref: ${{ github.head_ref }}`.
=> Update checkout actions

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/service-jms.yaml, src/main/charts/bamboo/values.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bamboo/values.yaml
This enables forwarding traffic to the pod's JMS port via Kubernetes service. There is a new variable `bamboo.service.jmsPort` to configure it. It enables traffic from remote agents outside of the Kubernetes cluster Bamboo is running in the same way SSH git connections are possible as explained here: https://atlassian.github.io/data-center-helm-charts/examples/bitbucket/BITBUCKET_SSH/
=> Enable Bamboo JMS traffic via Kubernetes Service

docs/docs/troubleshooting/LIMITATIONS.md
Follow-up PR to https://github.com/atlassian/data-center-helm-charts/pull/570
Now that Bamboo server JMS port can be exposed (and control separately from http server), the limitation needs to be removed from docs and replaced with instructions + warnings.
=> CLIP-1792: Change limitations statement on Bamboo server-agent comms

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/service-monitor.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/service-monitor-mesh.yaml, src/main/charts/bitbucket/templates/service-monitor.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/service-monitor.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/service-monitor.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/service-monitor.yaml, src/main/charts/jira/values.yaml, src/test/java/test/JmxMetricsTest.java, src/test/java/test/model/Kind.java
This PR adds [ServiceMonitors](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor) to DC Helm charts templates.
By default `monitoring.serviceMonitor.create=false` so it needs to be explicitly set to `true`.
Helm charts do not create `ServiceMonitor` CRDs, so it is expected that Kube API knows what a ServiceMonitor is (otherwise helm install/upgrade will fail).
Deploying [Kube prometheus stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) is one of the ways to deploy this CRD (but not the only one).
=> DCCLIP-501: Add optional ServiceMonitors to DC Helm Charts

src/main/charts/confluence/README.md, src/main/charts/confluence/grafana-dashboards/cache-clearing.json, src/main/charts/confluence/grafana-dashboards/cluster-locks.json, src/main/charts/confluence/grafana-dashboards/database-load.json, src/main/charts/confluence/grafana-dashboards/hikari.json, src/main/charts/confluence/grafana-dashboards/overview.json, src/main/charts/confluence/grafana-dashboards/plugin-monitoring.json, src/main/charts/confluence/grafana-dashboards/response-times.json, src/main/charts/confluence/templates/configmap-jmx-config.yaml, src/main/charts/confluence/templates/configmaps-grafana-dashboards.yaml, src/main/charts/confluence/values.yaml, src/test/java/test/JmxMetricsTest.java, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml
This PR adds optional configmaps with Grafana dashboard jsons. ConfigMaps are labeled as per values.yaml - labels must be known to Grafana dashboard importer sidecar.
Docs will be updated in https://github.com/atlassian/data-center-helm-charts/pull/572
=> DCLIP-509: Confluence Grafana Dashboards

docs/docs/userguide/CONFIGURATION.md, src/main/charts/bamboo/templates/service.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/templates/service.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/service.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/service.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/service.yaml, src/main/charts/jira/values.yaml, src/test/java/test/ServiceTest.java, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
This PR makes it possible to override service sessionAffinity (set to None by default). This can be necessary when no ingress controller is involved
Added a few simple unit tests and some docs.
=> CLIP-1804:Make sessionAffinity configurable for k8s services

src/main/charts/bitbucket/templates/config-jvm.yaml, src/main/charts/bitbucket/templates/service-jmx.yaml, src/main/charts/bitbucket/templates/service-monitor.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml
Bitbucket git operations are handled by a mesh sidecar that starts in a separate JVM. As a result, when javaagent with jmx_exporter jar and config is passed to Bitbucket JVM, none of mesh sidecar jmx metrics is exported, including one of the most important ones - tickets metrics.
This PR adds an additional port to jmx svc + an additional endpoint to ServiceMonitor, as well as passed an additional sysprop that mesh JVM will pick up. Metrics is then scraped on the same service, ports 9999 (bitbucket jvm) and 9998 (mesh sidecar).
There's not much sense in making mesh sidecar jmx port configurable, it will only expand values.yaml.
=> Pass javaagent with jmx_exporter config to Bitbucket Mesh JVM

src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/grafana-dashboards/build-actions-thread-pool-stats.json, src/main/charts/bitbucket/grafana-dashboards/db-ops.json, src/main/charts/bitbucket/grafana-dashboards/event-thread-pool-stats.json, src/main/charts/bitbucket/grafana-dashboards/git-ops.json, src/main/charts/bitbucket/grafana-dashboards/io-pump-thread-pool-stats.json, src/main/charts/bitbucket/grafana-dashboards/nio-pump-thread-pool-stats.json, src/main/charts/bitbucket/grafana-dashboards/overview.json, src/main/charts/bitbucket/grafana-dashboards/scheduled-thread-pool-stats.json, src/main/charts/bitbucket/grafana-dashboards/ssh-session-stats.json, src/main/charts/bitbucket/grafana-dashboards/ticket-status.json, src/main/charts/bitbucket/grafana-dashboards/webhooks-stats.json, src/main/charts/bitbucket/templates/configmap-jmx-config.yaml, src/main/charts/bitbucket/templates/configmaps-grafana-dashboards.yaml, src/main/charts/bitbucket/values.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml
This PR adds Bitbucket server dashboards from https://github.com/atlassian-labs/data-center-grafana-dashboards/pull/15
Other changes include:
* dashboard config in values.yaml
* README changes
* udated jmx config
* a template for dashboard configmaps which will look for akk .json files in grafana-dashboards directory in the chart root and create configmaps from them
=> DCCLIP-553: Add Bitbucket server dashboards to Helm chart

.github/workflows/kind.yaml, src/test/config/kind/common-values.yaml, src/test/scripts/kind/deploy_app.sh
Enabling dashboards in KinD common values to:
* ensure the number of created ConfigMaps == the number of json files in grafana-dashboards directory
* ensure content of the json file is identical to data.$key in the ConfigMap (this way we check that ConfigMaps are created with expected names, data keys and json content)
Example run: https://github.com/atlassian/data-center-helm-charts/actions/runs/5174426485/jobs/9320728709#step:12:1 (workflows run from PR are from main branch only)
=> DCCLIP-552: Add Grafana dashboard tests to KinD

.github/workflows/kind.yaml, src/main/scripts/process_dashboard.py, src/main/scripts/update_grafana_dashboards.sh
Now that https://github.com/atlassian-labs/data-center-grafana-dashboards/pull/19 and https://github.com/atlassian/data-center-helm-charts/pull/593 are merged, it's time to add Crowd to:
* KinD testing
* workflow that generates dashboard JSONs for crowd
=> Add crowd to dashboards CI

.github/workflows/update-lts-tags.yaml, src/test/scripts/product_versions.py, src/test/scripts/update_versions.py
Mesh is a bit different from other DC products as it's part of Bitbucket Helm chart, that's why it wasn't possible simply to add a new product to the list - hence adding a new function. Also, while appVersions for other products are changed in Chart.yaml, for Mesh it's Bitbucket's values.yaml. And it's a different place in expected output yaml, so it's not possible to reuse the existing functions.
Output from running the script:
```
I -------------------------------
I - Updating Bitbucket Mesh tag -
I -------------------------------
I Current version: 1.5.0
I New version: 2.0.1
I Updated values file: ../../main/charts/bitbucket/values.yaml
I Updated expected output file: ../resources/expected_helm_output/bitbucket/output.yaml
```
<details>
<summary>git diff</summary>
```
git diff
diff …
```
=> CLIP-1807: Update Bitbucket mesh tag

src/main/charts/confluence/templates/ingress.yaml
I swapped the position of the symphony ingress in the helm chart template. Priority-based ingresses like aws-elb/ alb are handled by the rule position in the ingress. You currently have to manually adjust the ingress to get the routing for syphony to work. This simple swap addresses the issue.
=> fix: swap ingress paths for priority based rules

src/main/charts/common/Chart.yaml, src/main/charts/common/templates/_jmx.tpl
If shared home isn't writable to other users, the init container will fail to copy jmx jar. The default bitnami image runs as 1001. This init container needs to run as root
=> Run jmx fetcher init container as root

src/main/charts/bamboo-agent/Chart.lock, src/main/charts/bamboo-agent/Chart.yaml, src/main/charts/bamboo/Chart.lock, src/main/charts/bamboo/Chart.yaml, src/main/charts/bitbucket/Chart.lock, src/main/charts/bitbucket/Chart.yaml, src/main/charts/confluence/Chart.lock, src/main/charts/confluence/Chart.yaml, src/main/charts/crowd/Chart.lock, src/main/charts/crowd/Chart.yaml, src/main/charts/jira/Chart.lock, src/main/charts/jira/Chart.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
See: https://github.com/atlassian/data-center-helm-charts/pull/606 which fixes fetching jmx jar if shared home permissions do not allow others to write.
=> Run jmx init container as root: get fix from common chart ver 1.2.3

src/main/charts/confluence/values.yaml, src/test/java/test/RequestsTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
Only container requests are supported in the config, but it is also very critical to specify the limits as well so the container doesn't crash other pods as when limits are not specified, the container can use all the resource available on the node.
As we want to make sure other pods are not affected in case of cpu or memory spikes, we need to be able to set the container limits as well.
Tested this out locally (uncommented):
kubectl get pod synchrony -n confluence -o=jsonpath='{.spec.containers[0].name}'
synchrony%                                                                                                                                                                           
kubectl get pod synchrony -n confluence -o=jsonpath='{.spec.containers[0].resources}' …
=> Synchrony missing container limits

src/main/charts/confluence/values.yaml, src/test/java/test/RequestsTest.java, src/test/resources/expected_helm_output/confluence/output.yaml
Keeping the [limits](https://github.com/atlassian/data-center-helm-charts/pull/615)  commented out and letting users decide. Also, a few CI jobs (including [e2e tests](https://github.com/atlassian/data-center-helm-charts/actions/runs/5538682764)) set their own requests which can be bigger than limits.
=> Unset default limits for Confluence

docs/docs/userguide/CONFIGURATION.md
See: https://github.com/atlassian/data-center-helm-charts/issues/612
Adding short docs on how to persist P1 plugins (in fact, any files from shared-home volume) in the container.
=> Add docs on how to mount P1 plugins

.github/pull_request_template.md
Bamboo jobs have been decommissioned, so removing them from PR template
=> Remove references to Atlassian CI

src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo-agent/templates/deployment-agent.yaml, src/main/charts/bamboo-agent/values.yaml, src/test/java/test/AdditionalFilesTest.java
Resolves https://github.com/atlassian/data-center-helm-charts/issues/579
Mounting files like maven's settings.xml is way easier with additionalFiles rather than with init containers and additional volume(-mounts).
=> Add additionalFiles to bamboo-agent Helm chart

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/statefulset.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/ReadinessLivenessProbesTest.java, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
In certain situations livenessProbes can be disruptive. This PR makes them off by default. Also, adding timeoutSeconds for both readiness and liveness probes.
=> Disable liveness probes by default, make timeoutSeconds configurable

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/configmaps-grafana-dashboards.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/configmap-mesh-grafana-dashboards.yaml, src/main/charts/bitbucket/templates/configmaps-grafana-dashboards.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/configmaps-grafana-dashboards.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/configmaps-grafana-dashboards.yaml, src/main/charts/jira/values.yaml
Addresses https://github.com/atlassian/data-center-helm-charts/issues/633
An annotation in the configmap can be a flag for dashboard importer sidecar to import a dashboard into a subdirectory.
=> Add annotations to Grafana dashboards ConfigMaps

src/main/charts/bamboo/templates/statefulset.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/templates/statefulset.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/templates/statefulset.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/templates/statefulset.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/templates/statefulset.yaml, src/main/charts/jira/values.yaml, src/test/java/test/AdditionalConfigMapsTest.java
We may want to make mounted files executable, so control over defaultMode will help. Other uses cases - security requirements that may enforce certain default modes.
=> Add defaultMode to additionalConfigMaps

src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/service-jmx.yaml, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/service-jmx.yaml, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/service-jmx.yaml, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/service-jmx.yaml, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/service-jmx.yaml, src/main/charts/jira/values.yaml, src/test/java/test/JmxMetricsTest.java
In certain scenarios it is necessary to have a different set of annotations for the main (server) svc and the jmx service. This PR introduces `monitoring.jmxServiceAnnotations` and a unit test case for it.
=> Decouple server and jmx svc annotations

.github/workflows/kind.yaml, .github/workflows/maven.yml, src/main/charts/bamboo-agent/README.md, src/main/charts/bamboo/README.md, src/main/charts/bamboo/templates/_helpers.tpl, src/main/charts/bamboo/values.yaml, src/main/charts/bitbucket/README.md, src/main/charts/bitbucket/templates/_helpers.tpl, src/main/charts/bitbucket/values.yaml, src/main/charts/confluence/README.md, src/main/charts/confluence/templates/_helpers.tpl, src/main/charts/confluence/values.yaml, src/main/charts/crowd/README.md, src/main/charts/crowd/templates/_helpers.tpl, src/main/charts/crowd/values.yaml, src/main/charts/jira/README.md, src/main/charts/jira/templates/_helpers.tpl, src/main/charts/jira/values.yaml, src/test/config/kind/common-values.yaml, src/test/java/test/VolumesTest.java, src/test/resources/expected_helm_output/bamboo-agent/output.yaml, src/test/resources/expected_helm_output/bamboo/output.yaml, src/test/resources/expected_helm_output/bitbucket/output.yaml, src/test/resources/expected_helm_output/confluence/output.yaml, src/test/resources/expected_helm_output/crowd/output.yaml, src/test/resources/expected_helm_output/jira/output.yaml
This PR added StatefulSet PVC retention policy to the charts. 
Local home PVC is created from StatefulSet PVC template. Before the change, local home PVC will not be deleted when product StatefulSet is deleted. This caused manual cleanup afterwards. With the [auto deletion feature](https://kubernetes.io/blog/2023/05/04/kubernetes-1-27-statefulset-pvc-auto-deletion-beta/) introduced by Kubernetes 1.27 as a beta feature, PVCs created by sts can now be linked with the lifecycle of sts, i.e. to be either deleted or retained when sts is scaled down or deleted.
=> CLIP-1799: StatefulSet PVC auto deletion

docs/docs/README.md, docs/docs/examples/EXAMPLES.md, docs/docs/examples/logging/efk/EFK.md, docs/docs/platforms/PLATFORMS.md, docs/docs/troubleshooting/LIMITATIONS.md, docs/docs/userguide/INSTALLATION.md, docs/docs/userguide/OPERATION.md, docs/docs/userguide/monitoring/PROMETHEUS.md, docs/mkdocs.yml
When testing other PR I found out that we have quite a lot of broken links in the docs. I went through them and fixed them (they were reporting 404).
=> Fix broken links in the documentation

docs/docs/containers/BITBUCKET-MESH.md, docs/docs/containers/BITBUCKET.md, docs/docs/containers/CROWD.md
This PR moved Bitbucket Mesh docker README here. 
It was a missing part from https://github.com/atlassian/data-center-helm-charts/pull/774 .
=> CLIP-1859: Added Bitbucket Mesh docker image docs.

docs/docs/containers/BAMBOO-AGENT.md, docs/docs/containers/BAMBOO.md, docs/docs/containers/BITBUCKET-MESH.md, docs/docs/containers/BITBUCKET.md, docs/docs/containers/CONFLUENCE.md, docs/docs/containers/CROWD.md, docs/docs/containers/JIRA.md
As every container uses `shared-components` we can spread the good news about `VERBOSE_LOGS`
=> BAM-25729: Document VERBOSE_LOGS everywhere as all images use shared-components

docs/docs/containers/BAMBOO.md
Use generic oracle as a DB Type instead of a hardcoded oracle12c
- [-] I have added unit tests
- [-] I have applied the change to all applicable products
- [-] The E2E test has passed (use `e2e` label)
=> Encourage ATL_DB_TYPE=oracle instead of oracle12c

.github/workflows/e2e-tf-deployment.yaml
`actions/upload-artifact@v2` is deprecated and caused e2e test to fail. This PR updated this action to a newer version that's used in the repo.
=> CLIP-1916: Update actions/upload-artifact version

docs/docs/containers/BAMBOO-AGENT.md, docs/docs/containers/BAMBOO.md
Adds maxHttpHeaderSize and URIEncoding as environ-configurable properties
Updates Bamboo READMES to become closer to the current implementation
- [-] I have added unit tests
- [-] The E2E test has passed (use `e2e` label)
=> BAM-25942: Make maxHttpHeader size configurable

docs/docs/containers/BAMBOO-AGENT.md, docs/docs/containers/BAMBOO.md
Prepare for Bamboo 10.1.0 - Add support for JDK21
- [-] I have added unit tests
- [-] I have applied the change to all applicable products
- [-] The E2E test has passed (use `e2e` label)
=> BDEV-19172: Add support for JDK21

docs/docs/examples/storage/STORAGE.md, docs/docs/examples/storage/nfs/NFS.md, docs/docs/userguide/CONFIGURATION.md, docs/docs/userguide/PREREQUISITES.md, src/main/charts/bitbucket/values.yaml
Historically we required a dedicated NFS server to store shared home as it contained the `git` data. With the introduction of BB Mesh, this is no longer the case. The documentation updates reflect relaxed requirements in case the Bitbucket Mesh is deployed.
=> Update documentation related to Bitbucket shared home requirements

docs/docs/examples/bitbucket/BITBUCKET_AWS_OPENSEARCH.md, docs/docs/examples/bitbucket/BITBUCKET_OPENSEARCH.md, docs/docs/examples/bitbucket/BITBUCKET_SESSION_AFFINITY.md, docs/docs/userguide/CONFIGURATION.md
_- Added documentation for AWS OpenSearch Service configuration in `BITBUCKET_OPENSEARCH.md`
- Simple configuration example using environment variables
- Secret creation for credentials
- IAM authentication option
- Added clear example for NGINX Ingress session stickiness in `CONFIGURATION.md`
- Default configuration (automatically enabled)
- Custom cookie configuration options_
=> Updating documentation with AWS OpenSearch and Stickiness config details. 
